version: 2.1

jobs:
  fetch_files:
    parallelism: 10
    circleci_ip_ranges: true
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Fetch files
          command: |
            # try wget to download JSON file
            wget -c https://dnsjson.com/jobs.knownips.circleci.com/A.json
            jq "." A.json

workflows:
  main:
    jobs:
      - fetch_files
